version: "3.7"

services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile

    container_name: dev_comu_backend

    restart: always

    ports:
      - 8000:8000

    env_file:
      - .env

    depends_on:
      - db

    volumes:
      - .:/usr/src/dev_comu

    networks:
      - dev_comu_net

    command: >
      sh -c "python manage.py makemigrations && python maange.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8.0
    restart: always
    container_name: dev_comu_db
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Seoul

    volumes:
      - db_volume:/var/lib/mysql

    networks:
      - dev_comu_net

networks:
 dev_comu_net:

volumes: # 볼륨을 따로 생성
  db_volume: