version: "3"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile

    container_name: dev_comu_backend

    restart: always

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - db
    
    volumes:
      - ./:/dev_comu/

    working_dir: /dev_comu/

    networks:
      - dev_comu_net

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql
    restart: always
    container_name: dev_comu_db
    ports:
      - "3306:3306"
    
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_NAME=${MYSQL_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    volumes:
      - ./mysql/data:/var/lib/mysql/data

    networks:
      - dev_comu_net

networks:
 dev_comu_net: