# Generated by Django 4.0 on 2022-03-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd_chg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
