# Generated by Django 4.0 on 2022-03-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dormant_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='need_chg_pwd',
            field=models.BooleanField(default=False),
        ),
    ]
