# Generated by Django 4.0 on 2022-03-01 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_dormant_account_user_need_chg_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dormant', to='accounts.user')),
            ],
            options={
                'db_table': 'user_dormant',
            },
        ),
    ]
